//! Golden trajectory parity against the Python reference (PLAN.md M2 exit
//! criterion: per-iteration parity on a tiny fixed problem over 12 iters).
//!
//! Inputs are generated by a deterministic sin-formula both sides implement
//! identically (no RNG stream replication). The expected values below were
//! produced by `sheaf_admm.admm.run_admm_history` (JAX fp32) with:
//! FixedGeometry over edges [[0,1],[0,2],[1,3],[2,3],[0,3]], N=4, B=2, d_v=4,
//! d_e=2; DiagonalProxXSolver with the L1+box objective (lower=0); prox-mode
//! UnrolledCG gamma=5, T=5; rho=0.25, alpha=1.0, K=12.

// Golden literals are verbatim fp32 dumps from the Python run.
#![allow(clippy::excessive_precision)]

mod common;

use common::*;

use ndarray::{s, Array3, Array4};
use sheaf_core::admm::{run_admm_history, AdmmParams, XSolverKind};
use sheaf_core::geometry::FixedGeometry;
use sheaf_core::solvers::{EncoderOutput, Objective, UnrolledCgParams, ZMode};

const N: usize = 4;
const B: usize = 2;
const D_V: usize = 4;
const D_E: usize = 2;
const K: usize = 12;

/// `sin(7*i0 + 3*i1 + 5*i2 + 1*i3 + off) * scale`, all in f32 — mirrors the
/// generator in the Python golden script exactly.
fn arr3(shape: (usize, usize, usize), off: f32, scale: f32) -> Array3<f32> {
    Array3::from_shape_fn(shape, |(i, j, k)| {
        ((i as f32) * 7.0 + (j as f32) * 3.0 + (k as f32) * 5.0 + off).sin() * scale
    })
}

fn arr4(shape: (usize, usize, usize, usize), off: f32, scale: f32) -> Array4<f32> {
    Array4::from_shape_fn(shape, |(i, j, k, l)| {
        ((i as f32) * 7.0 + (j as f32) * 3.0 + (k as f32) * 5.0 + (l as f32) + off).sin() * scale
    })
}

#[rustfmt::skip]
const GOLDEN_CRMS: [[f32; 2]; K] = [
    [0.00919435, 0.01890177],
    [0.01879668, 0.03304939],
    [0.02738254, 0.04211304],
    [0.03357458, 0.04755530],
    [0.03780860, 0.05070177],
    [0.04065284, 0.05274919],
    [0.04260291, 0.05420841],
    [0.04396980, 0.05518501],
    [0.04494540, 0.05579910],
    [0.04565138, 0.05614865],
    [0.04616830, 0.05630910],
    [0.04655064, 0.05633727],
];

#[rustfmt::skip]
const GOLDEN_PRIMAL_MEAN: [f32; K] = [
    0.51889408, 0.43645972, 0.31770390, 0.21610615, 0.15252194, 0.11061320,
    0.08259733, 0.06315878, 0.05011985, 0.04141647, 0.03540945, 0.03118247,
];

#[rustfmt::skip]
const GOLDEN_DUAL_MEAN: [f32; K] = [
    0.20350307, 0.02242500, 0.01798391, 0.01753942, 0.01210922, 0.00821304,
    0.00547488, 0.00405881, 0.00300545, 0.00227897, 0.00174620, 0.00136060,
];

#[rustfmt::skip]
const GOLDEN_FINAL_X: [f32; N * B * D_V] = [
    0.00000000, 0.00000000, 0.00000000, 0.14396203, 0.14924218, 0.00000000,
    0.00000000, 0.00000000, 0.12485839, 0.00000000, 0.00000000, 0.25240767,
    0.00000000, 0.16065405, 0.00000000, 0.00000000, 0.26753190, 0.00000000,
    0.00000000, 0.30807245, 0.00000000, 0.17733698, 0.00000000, 0.00000000,
    0.36192754, 0.00000000, 0.00000000, 0.23492269, 0.00000000, 0.00000000,
    0.03566497, 0.00000000,
];

#[rustfmt::skip]
const GOLDEN_FINAL_Z: [f32; N * B * D_V] = [
    0.01769522, -0.00926296, -0.02770185, 0.12328799, 0.11897113, -0.03900445,
    -0.01187766, 0.02616949, 0.13634802, -0.00154555, -0.01316038, 0.23973314,
    -0.01421241, 0.15029313, 0.00301864, 0.01362147, 0.26670611, -0.01143403,
    -0.01152997, 0.30704677, -0.01650172, 0.16781731, 0.00621580, 0.01623641,
    0.36047167, -0.00813568, -0.00733518, 0.23513114, -0.02857350, -0.03830033,
    0.02285232, 0.02445410,
];

#[rustfmt::skip]
const GOLDEN_FINAL_Y: [f32; N * B * D_V] = [
    -1.58825135, -0.37072557, 1.18764317, 1.65409887, 1.52269292, 1.63002646,
    0.23871952, -1.37206399, -1.06775320, -0.34217680, 0.69799584, 1.09643352,
    0.82194507, 1.62445092, 0.93344450, -0.61576724, 0.24548453, 0.33283144,
    0.11417463, -0.20945376, 0.06506842, 1.27362931, 1.31122196, 0.14328220,
    1.27848554, 0.74877816, -0.46935260, -1.25596178, -0.20412573, 1.53322494,
    1.86093307, 0.47771111,
];

#[test]
fn golden_trajectory_matches_python_reference() {
    let graph = tiny_graph(); // edges [[0,1],[0,2],[1,3],[2,3],[0,3]]
    let e = graph.num_edges();
    let maps = arr4((e, 2, D_E, D_V), 0.1, 0.6);
    let geo = FixedGeometry::new(graph, maps);

    let z_init = arr3((N, B, D_V), 0.7, 0.5);
    let q_diag = arr3((N, B, D_V), 1.3, 0.5).mapv(|v| v.abs() + 0.1);
    let q = arr3((N, B, D_V), 2.1, 0.5);
    let l1 = arr3((N, B, D_V), 3.3, 0.05).mapv(f32::abs);
    let upper = arr3((N, B, D_V), 4.7, 0.5).mapv(|v| v.abs() + 0.5);

    let enc = EncoderOutput {
        h: z_init.clone(),
        objective: Objective::L1Box { q_diag, q, l1, upper },
        lora: None,
    };
    let z_params = UnrolledCgParams {
        mode: ZMode::Prox,
        gamma: 5.0,
        num_iters: 5,
        tikhonov_eps: 1e-5,
    };
    let params = AdmmParams { rho: 0.25, alpha: 1.0, gamma: 5.0, k: K };

    let (state, hist) =
        run_admm_history(&enc, &geo, XSolverKind::DiagonalProx, &z_params, &params, &z_init);

    // Widening tolerance schedule (PLAN.md §5.2): fp32 accumulation-order
    // drift compounds over the unroll; 12 iters stays well within 1e-5-ish.
    for k in 0..K {
        #[allow(clippy::needless_range_loop)]
        for b in 0..B {
            let got = hist.consistency_rms[[k, b]];
            let want = GOLDEN_CRMS[k][b];
            assert!(
                (got - want).abs() <= 2e-6,
                "consistency_rms[{k},{b}]: {got} vs golden {want}"
            );
        }
        let p_mean = hist.primal_res.slice(s![k, .., ..]).mean().unwrap();
        assert!(
            (p_mean - GOLDEN_PRIMAL_MEAN[k]).abs() <= 5e-6,
            "primal_res mean[{k}]: {p_mean} vs golden {}",
            GOLDEN_PRIMAL_MEAN[k]
        );
        let d_mean = hist.dual_res.slice(s![k, .., ..]).mean().unwrap();
        assert!(
            (d_mean - GOLDEN_DUAL_MEAN[k]).abs() <= 5e-6,
            "dual_res mean[{k}]: {d_mean} vs golden {}",
            GOLDEN_DUAL_MEAN[k]
        );
    }

    for (i, ((&gx, &gz), &gy)) in state
        .x
        .iter()
        .zip(state.z.iter())
        .zip(state.y.iter())
        .enumerate()
    {
        assert!(
            (gx - GOLDEN_FINAL_X[i]).abs() <= 2e-5,
            "final x[{i}]: {gx} vs golden {}",
            GOLDEN_FINAL_X[i]
        );
        assert!(
            (gz - GOLDEN_FINAL_Z[i]).abs() <= 2e-5,
            "final z[{i}]: {gz} vs golden {}",
            GOLDEN_FINAL_Z[i]
        );
        assert!(
            (gy - GOLDEN_FINAL_Y[i]).abs() <= 5e-5,
            "final y[{i}]: {gy} vs golden {}",
            GOLDEN_FINAL_Y[i]
        );
    }
}
